

TIMESHEET_STATUS = {
    "DRAFT": 1,
    "PENDING_APPROVAL": 2,
    "APPROVED": 3,
    "REJECTED": 4,
    "CANCEL": 5,
    "LOCKED": 6,
    "IN_PROGRESS": 7
}

TIMESHEET_APPROVE_REJECT_VARIANT = {
    "APPROVE" 
    "REJECT"
}