"""Added unique timesheets

Revision ID: 0f02f5771f15
Revises: 4a41bcb3bb9a
Create Date: 2025-12-15 16:30:05.846018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f02f5771f15'
down_revision = '4a41bcb3bb9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timesheets', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_week', ['user_id', 'week_start', 'week_end'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timesheets', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_week', type_='unique')

    # ### end Alembic commands ###
