"""Added status to timesheet entry table

Revision ID: 1c352ba832d5
Revises: ebc3c8e766d3
Create Date: 2025-12-05 14:06:09.551086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c352ba832d5'
down_revision = 'ebc3c8e766d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timesheet_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'timesheet_status', ['status'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timesheet_entries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
