"""removed nullable false

Revision ID: 4a41bcb3bb9a
Revises: 1c352ba832d5
Create Date: 2025-12-05 14:06:38.822679

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a41bcb3bb9a'
down_revision = '1c352ba832d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timesheet_entries', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timesheet_entries', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
