"""Added type to holiday table

Revision ID: 62f68c114d8d
Revises: e57457664087
Create Date: 2026-01-05 16:39:17.860100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62f68c114d8d'
down_revision = 'e57457664087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('PUBLIC', 'FLOATER', name='holiday_type_enum'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
