"""timesheet reminder table change

Revision ID: 8ed9092e626f
Revises: 689036463aa1
Create Date: 2026-01-09 18:00:19.765133

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ed9092e626f'
down_revision = '689036463aa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timesheet_reminders', schema=None) as batch_op:
        batch_op.alter_column('reminder_type',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('GENTLE', 'SECOND', 'THIRD', name='reminder_type_enum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timesheet_reminders', schema=None) as batch_op:
        batch_op.alter_column('reminder_type',
               existing_type=sa.Enum('GENTLE', 'SECOND', 'THIRD', name='reminder_type_enum'),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
