"""Changed the timesheet models

Revision ID: ebc3c8e766d3
Revises: c45d0fffaf0e
Create Date: 2025-12-05 11:35:50.774710

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ebc3c8e766d3'
down_revision = 'c45d0fffaf0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timesheet_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=36), nullable=False),
    sa.Column('timesheet_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.Column('time_records', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['timesheet_id'], ['timesheets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('timesheet_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timesheet_entry_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('timesheet_history_ibfk_4'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'timesheet_entries', ['timesheet_entry_id'], ['id'])
        batch_op.drop_column('timesheet_id')

    with op.batch_alter_table('timesheets', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('timesheets_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('timesheets_ibfk_4'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('timesheets_ibfk_2'), type_='foreignkey')
        batch_op.drop_column('approver_id')
        batch_op.drop_column('project_id')
        batch_op.drop_column('task_id')
        batch_op.drop_column('time_records')
        batch_op.drop_column('comment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timesheets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('time_records', mysql.JSON(), nullable=False))
        batch_op.add_column(sa.Column('task_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('approver_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('timesheets_ibfk_2'), 'projects', ['project_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('timesheets_ibfk_4'), 'tasks', ['task_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('timesheets_ibfk_1'), 'users', ['approver_id'], ['id'])

    with op.batch_alter_table('timesheet_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timesheet_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('timesheet_history_ibfk_4'), 'timesheets', ['timesheet_id'], ['id'])
        batch_op.drop_column('timesheet_entry_id')

    op.drop_table('timesheet_entries')
    # ### end Alembic commands ###
